#!/bin/bash

function timer {
	printf "FROM:\t%s\n" $(date -Iseconds)
	printf "TO:\t%s\n" $(date -Iseconds --date="$1 seconds")

	for i in $(seq $1); do
		sleep 1
		minutes=$((($1 - $i) / 60))
		seconds=$((($1 - $i) % 60))
		printf "残り:\t%s分 %s秒\r" $minutes $seconds
	done

}

function dialog {
	kdialog --title 蕃茄 --yesnocancel $1 --yes-label "25分" --no-label "5分" --cancel-label "終了" 2> /dev/null

	case $? in
		0)
			timer 1500
			;;
		1)
			timer 300
			;;
		2)
			exit
			;;
	esac
}

dialog "時間を選んでね!"

while true; do
	dialog "そこまで!"
done
